name: ItemDetector
main: org.cubeville.itemdetector.ItemDetector
version: ${project.version}
authors: [Cubeville, GoalieGuy6]
description: Creates pressure plates that can detect and remove items from a player inventory

commands:
    itemdetector:
        aliases: [detector]
	description: Create/modify item detector plates
	usage: /<command>